import type { GetServerSideProps } from "next";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Feed from "../components/Feed";
import SideBar from "../components/SideBar";
import Widgets from "../components/Widgets";
import { Tweet } from "../typings";
import { fetchTweets } from "../utils/fetchTweets";

interface tweetProps {
  tweets: Tweet[];
}

const Home = ({ tweets }: tweetProps) => {
  // console.log(tweets);

  return (
    <div className="lg:max-w-6xl mx-auto">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.pixabay.com/photo/2018/06/22/19/03/logo-3491390_960_720.png"
        />
      </Head>
      <Toaster />
      <main className="grid grid-cols-9">
        {/* sidebar */}
        <SideBar />

        {/* feed */}
        <Feed tweets={tweets} />

        {/* widgets */}
        <Widgets />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  // only accepts absolute paths
  const NEXT_BASE_URL = "http://localhost:3000";

  const tweets = await fetchTweets();

  // response fromsanity backend
  // console.log(tweets);
  return {
    props: { tweets },
  };
};
