import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.pixabay.com/photo/2018/06/22/19/03/logo-3491390_960_720.png" />
      </Head>
      <h2>home scrren</h2>
    </div>
  );
};

export default Home;
